name: Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Set up Go
        uses: actions/setup-go@v5.4
        with:
          go-version: 1.24.1

      - name: Execute golangci-lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: v2.0

      - name: Run tests
        run: go test ./...

